theme: jekyll-theme-minimal
title: 'Introduction to R for Bioinformatics'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Introduction to the Workshop and the Core
    url: base/welcome

   - heading: Course Materials 
   - title: Introduction to ggplot2 and box plots 
     url: R/01-boxplot
  # - title: Introduction to R Day 2
  #   url: R/Intro2R_day2
  # - title: Introduction to R Day 3
  #   url: R/Intro2R_day3

  # - title: Challenge solutions
  #   url: R/challenge_solutions

  - title: ggplot2 and scatterplots
    url: R/01-scatterplot

  - heading: ETC
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2025-August-Intermediate-Visualization-for-Bioinformatics
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
